BooksLibrary/Models/BookViewModels/BookIsNotAvailableViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BooksLibrary.Models.BookViewModels
{
    public class BookIsNotAvailableViewModel
    {
        public BookViewModel Book { get; set; }
        public DateTime PropablyBookAvailableDate { get; set; }
    }
}

BooksLibrary/Controllers/BookController.cs
using AutoMapper;
using BooksLibrary.Business.Models;
using BooksLibrary.Business.Service;
using BooksLibrary.Models;
using BooksLibrary.Models.BookViewModels;
using PagedList;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;

namespace BooksLibrary.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        private readonly IBookService bookService;
        private readonly ICategoryService categoryService;
        private readonly IMapper mapper;
        public BookController(IBookService bs, ICategoryService cs, IMapper map)
        {
            bookService = bs;
            categoryService = cs;
            mapper = map;
        }

        [AllowAnonymous]
        public ActionResult Index(int? page, string searchBook, string searchAuthor, string sortOrder, string categoryFilter)
        {
            int pageNumber = page ?? 1;
            int pageSize = 10;
            int totalCount;
            string[] includeProperties = { "BookCategory" };

            ViewBag.SearchBook = searchBook;
            ViewBag.SearchAuthor = searchAuthor;
            ViewBag.SortOrder = sortOrder;
            ViewBag.CategoryFilter = categoryFilter;

            IEnumerable<Book> query = bookService.GetAllBooks(CreateSearchFilter(searchBook, searchAuthor, categoryFilter), includeProperties, SelectSortOrder(sortOrder), out totalCount, pageNumber, pageSize);
            IEnumerable<IndexAllBooksViewModel> booksViewModel = mapper.Map<IEnumerable<IndexAllBooksViewModel>>(query);
            var books = new StaticPagedList<IndexAllBooksViewModel>(booksViewModel, pageNumber, pageSize, totalCount);

            return View(books);
        }

        private Expression<Func<Book, bool>> CreateSearchFilter(string searchBook, string searchAuthor, string categoryFilter)
        {
            Expression<Func<Book, bool>> filter = null;

            if (!string.IsNullOrEmpty(searchBook) && !string.IsNullOrEmpty(searchAuthor) && !string.IsNullOrEmpty(categoryFilter))
            {
                filter = f => f.Title.ToUpper().Contains(searchBook.ToUpper()) && f.Author.ToUpper().Contains(searchAuthor.ToUpper()) && f.BookCategory.CategoryName == categoryFilter;
            }
            else if (!string.IsNullOrEmpty(searchBook) && !string.IsNullOrEmpty(searchAuthor) && string.IsNullOrEmpty(categoryFilter))
            {
                filter = f => f.Title.ToUpper().Contains(searchBook.ToUpper()) && f.Author.ToUpper().Contains(searchAuthor.ToUpper());
            }
            else if (!string.IsNullOrEmpty(searchBook) && string.IsNullOrEmpty(searchAuthor) && !string.IsNullOrEmpty(categoryFilter))
            {
                filter = f => f.Title.ToUpper().Contains(searchBook.ToUpper()) && f.BookCategory.CategoryName == categoryFilter;
            }
            else if (string.IsNullOrEmpty(searchBook) && !string.IsNullOrEmpty(searchAuthor) && !string.IsNullOrEmpty(categoryFilter))
            {
                filter = f => f.Author.ToUpper().Contains(searchAuthor.ToUpper()) && f.BookCategory.CategoryName == categoryFilter;
            }
            else if (!string.IsNullOrEmpty(searchAuthor))
            {
                filter = f => f.Author.ToUpper().Contains(searchAuthor.ToUpper());
            }
            else if (!string.IsNullOrEmpty(searchBook))
            {
                filter = f => f.Title.ToUpper().Contains(searchBook.ToUpper());
            }
            else if (!string.IsNullOrEmpty(categoryFilter))
            {
                filter = f => f.BookCategory.CategoryName == categoryFilter;
            }

            return filter;
        }

        private Func<IQueryable<Book>, IOrderedQueryable<Book>> SelectSortOrder(string sortOrder)
        {
            Func<IQueryable<Book>, IOrderedQueryable<Book>> orderBy = null;
            switch (sortOrder)
            {
                case "title":
                    orderBy = q => q.OrderBy(b => b.Title);
                    break;
                case "author":
                    orderBy = q => q.OrderBy(b => b.Author);
                    break;
                default:
                    orderBy = q => q.OrderBy(b => b.BookId);
                    break;
            }

            return orderBy;
        }

        [Authorize(Roles = "Admin")]
        public ActionResult IndexBookManagement(int? page, string searchBook, string searchAuthor, string categoryFilter)
        {
            int pageNumber = page ?? 1;
            int pageSize = 10;
            int totalCount;
            ViewBag.SearchBook = searchBook;
            ViewBag.SearchAuthor = searchAuthor;

            string category;
            if (string.IsNullOrEmpty(categoryFilter))
            {
                category = categoryService.GetAllCategories().FirstOrDefault().CategoryName;
            }
            else
            {
                category = categoryFilter;
            }
            ViewBag.CategoryFilter = category;

            IEnumerable<Book> query = bookService.GetAllBooks(CreateSearchFilter(searchBook, searchAuthor, category), null, q => q.OrderBy(b => b.Title), out totalCount, pageNumber, pageSize);

            IEnumerable<BookViewModel> booksModel = mapper.Map<IEnumerable<BookViewModel>>(query);

            var allBooks = new StaticPagedList<BookViewModel>(booksModel, pageNumber, pageSize, totalCount);

            return View(allBooks);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult AddBook()
        {
            PopulateViewBagWithYears();
            PopulateViewBagWithCategories();
            return View();
        }

        private void PopulateViewBagWithYears()
        {
            var years = Enumerable.Range(1975, (DateTime.Now.Year - 1975) + 1).Select(year => new SelectListItem
                {
                    Value = year.ToString(CultureInfo.InvariantCulture),
                    Text = year.ToString(CultureInfo.InvariantCulture)
                });
            ViewBag.Years = years;
        }

        private void PopulateViewBagWithCategories()
        {
            var categories = categoryService.GetAllCategories().ToList();
            ViewBag.Categories = categories;
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult AddBook(BookViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Book book = mapper.Map<Book>(viewModel);
                bookService.AddBook(book);
                TempData["message"] = "Książka została dodana!";
                return RedirectToAction("IndexBookManagement");
            }
            return View(viewModel);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult EditBook(int bookId)
        {
            Book book = bookService.FindBook(bookId);

            if (book == null)
                return HttpNotFound();

            BookViewModel bookModel = mapper.Map<BookViewModel>(book);
            PopulateViewBagWithYears();
            PopulateViewBagWithCategories();
            return View(bookModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult EditBook(BookViewModel bookModel, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                Book book = mapper.Map<Book>(bookModel);
                bookService.UpdateBook(book);
                TempData["message"] = "Zmiany zostały zapisane!";
                return RedirectToReferrerUrl(returnUrl);
            }
            return View(bookModel);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult DeleteBook(int bookId)
        {
            Book book = bookService.FindBook(bookId);
            if (book == null)
                return HttpNotFound();

            ViewBag.ReturnUrl = Request.UrlReferrer;

            BookViewModel bookModel = mapper.Map<BookViewModel>(book);

            return View(bookModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ActionName("DeleteBook")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteBookConfirm(int bookId, string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;

            if (bookService.BookExistsInRents(bookId))
            {
                Book book = bookService.FindBook(bookId);
                BookViewModel bookModel = mapper.Map<BookViewModel>(book);
                ModelState.AddModelError("", "Nie można usunąć wybranej książki, ponieważ jest ona wypożyczona!");
                return View(bookModel);
            }

            if (bookService.BookExistsInReservations(bookId))
            {
                Book book = bookService.FindBook(bookId);
                BookViewModel bookModel = mapper.Map<BookViewModel>(book);
                ModelState.AddModelError("", "Nie można usunąć wybranej książki, ponieważ jest ona zarezerwowana!");
                return View(bookModel);
            }

            bookService.DeleteBook(bookId);
            TempData["message"] = "Książka została usunięta!";
            return RedirectToReferrerUrl(returnUrl);
        }

        [AllowAnonymous]
        public ActionResult Details(int bookId)
        {
            Book book = bookService.FindBook(bookId);

            if (book == null)
                return HttpNotFound();

            BookViewModel bookModel = mapper.Map<BookViewModel>(book);
            return View(bookModel);
        }

        public ActionResult BookIsNotAvailable(int bookId)
        {
            Book book = bookService.FindBook(bookId);

            if (book == null)
                return HttpNotFound();

            var date = bookService.GetPropablyBookAvailableDate(bookId);

BooksLibrary/Controllers/CategoryController.cs
using BooksLibrary.Business.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BooksLibrary.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService categoryService;
        public CategoryController(ICategoryService cs)
        {
            categoryService = cs;
        }

        public PartialViewResult CategoriesPartial(string selectedCategory, bool management)
        {
            ViewBag.CategoryFilter = selectedCategory;

            string actionName;
            if (management == true)
                actionName = "IndexBookManagement";
            else
                actionName = "Index";
            ViewBag.Action = actionName;

            var categories = categoryService.GetAllCategories().ToList();
            return PartialView("_CategoriesPartial", categories);
        }

        protected override void Dispose(bool disposing)
        {
            categoryService.Dispose();
            base.Dispose(disposing);
        }
    }
}

BooksLibrary/Controllers/ReservationController.cs
using AutoMapper;
using BooksLibrary.Business.Models;
using BooksLibrary.Business.SecurityServices;
using BooksLibrary.Business.Service;
using BooksLibrary.Models.BookViewModels;
using BooksLibrary.Models.ReservationViewModels;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace BooksLibrary.Controllers
{
    [Authorize]
    public class ReservationController : Controller
    {
        private readonly IReservationService reservationService;
        private readonly IMapper mapper;
        private readonly IBookService bookService;
        private readonly IRentService rentService;
        private readonly IUserService userService;
        public ReservationController(IReservationService service, IMapper map, IBookService bookSer, IRentService rentS, IUserService userSer)
        {
            reservationService = service;
            mapper = map;
            bookService = bookSer;
            rentService = rentS;
            userService = userSer;
        }

        public ActionResult IndexUserReservations(int? bookId)
        {
            if (bookId != null)
            {
                ViewBag.BookID = bookId;
                ModelState.AddModelError("", "Wybrana książka jest już przez Ciebie zarezerwowana!");
            }

            int userId = userService.CurrentUserId();
            IEnumerable<Reservation> reservations = reservationService.GetAllReservations(u => u.UserId == userId, new string[] {"Book"});

            IEnumerable<UserReservationsViewModel> allUserReservations = mapper.Map<IEnumerable<UserReservationsViewModel>>(reservations);

            return View(allUserReservations);
        }

        public ActionResult AddReservation(int bookId)
        {
            Book book = bookService.FindBook(bookId);

            if (book == null)
                return HttpNotFound();

            if (book.Quantity == 0)
                return RedirectToAction("BookIsNotAvailable", "Book", new { bookId = bookId });

            BookViewModel bookModel = mapper.Map<BookViewModel>(book);
            return View(bookModel);
        }

        [HttpPost,ActionName("AddReservation")]
        [ValidateAntiForgeryToken]
        public ActionResult ConfirmReservation(int bookId, string returnUrl)
        {
            int userId = userService.CurrentUserId();
            Reservation reservation = new Reservation();
            reservation.UserId = userId;
            reservation.BookId = bookId;
            reservation.ReservationDate = DateTime.Now;
            reservation.DateOfReceipt = DateTime.Now.AddDays(1);

            if (!userService.UserAddressExists(userId))
                return RedirectToAction("AddAddress", "Account");

            if(reservationService.ReservationExists(userId,bookId))
                return RedirectToAction("IndexUserReservations", new { bookId = bookId });

            if(rentService.RentExists(userId,bookId))
                return RedirectToAction("IndexUserRents", "Rent", new { bookId = bookId });

            if (!bookService.BookIsAvailable(bookId))
                return RedirectToAction("BookIsNotAvailable", "Book", new { bookId = bookId });

            reservationService.AddReservation(reservation);
            TempData["message"] = "Książka została zarezerwowana!";
            return RedirectToReferrerUrl(returnUrl);
        }

        public ActionResult DeleteReservation(int reservationId)
        {
            Reservation reservation = reservationService.FindReservation(reservationId);

            if (reservation == null)
                return HttpNotFound();

            ReservationViewModel reservationModel = mapper.Map<ReservationViewModel>(reservation);

            return View(reservationModel);
        }

        [HttpPost, ActionName("DeleteReservation")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteReservationConfirm(int reservationId)
        {
            Reservation reservation = reservationService.FindReservation(reservationId);
            if (reservation == null)
            {
                TempData["message"] = "Rezerwacja nie istnieje lub została już anulowana!";
            }
            else
            {
                reservationService.DeleteReservation(reservationId);
                TempData["message"] = "Rezerwacja została anulowana!";
            }
            return RedirectToAction("IndexUserReservations");
        }

        [AllowAnonymous]
        public ActionResult RedirectToReferrerUrl(string returnUrl)
        {
            if (!string.IsNullOrEmpty(returnUrl))
                return Redirect(returnUrl);
            else
                return RedirectToAction("Index", "Book");
        }

        protected override void Dispose(bool disposing)
        {
            reservationService.Dispose();
            bookService.Dispose();
            rentService.Dispose();
            base.Dispose(disposing);
        }
    }
}

BooksLibrary/Views/Book/AddBook.cshtml
@model BooksLibrary.Models.BookViewModels.BookViewModel

@{
    ViewBag.Title = "Dodaj książkę";
}

<h2>Dodaj książkę</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Książka</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field-add-book">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Author)
        </div>
        <div class="editor-field-add-book">
            @Html.EditorFor(model => model.Author)
            @Html.ValidationMessageFor(model => model.Author)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ISBN)
        </div>
        <div class="editor-field-add-book">
            @Html.EditorFor(model => model.ISBN)
            @Html.ValidationMessageFor(model => model.ISBN)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PublishingHouse)
        </div>
        <div class="editor-field-add-book">
            @Html.EditorFor(model => model.PublishingHouse)
            @Html.ValidationMessageFor(model => model.PublishingHouse)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryId)
        </div>
        <div class="editor-field-add-book">
            @Html.DropDownListFor(model => model.CategoryId, new SelectList(ViewBag.Categories, "CategoryId", "CategoryName"),"Wybierz...")
            @Html.ValidationMessageFor(model => model.CategoryId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ReleaseDate)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.ReleaseDate, new SelectList(ViewBag.Years, "Value", "Text"), "Wybierz...")
            @Html.ValidationMessageFor(model => model.ReleaseDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Quantity)
        </div>
        <div class="editor-field-number">
            @Html.EditorFor(model => model.Quantity)
            @Html.ValidationMessageFor(model => model.Quantity)
        </div>

        <br />
        <p>
            <input type="submit" value="Zapisz" class="button" />
            @Html.ActionLink("Anuluj", "IndexBookManagement", null, new { @class = "button" })
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BooksLibrary/Views/Book/BookIsNotAvailable.cshtml
@model BooksLibrary.Models.BookViewModels.BookIsNotAvailableViewModel

@{
    ViewBag.Title = "Książka niedostępna";
}

<h2>Książka niedostępna</h2>

<h4>Wybrana przez Ciebie książka jest w tej chwili niedostępna.</h4>

<fieldset>
    <legend>Książka</legend>
    <table>
        <tr>
            <td>
                @Html.DisplayFor(model => model.Book.Title)
            </td>
            <td>
                @Html.DisplayFor(model => model.Book.Author)
            </td>
            <td>
                @Html.DisplayFor(model => model.Book.ISBN)
            </td>
            <td>
                @Html.DisplayFor(model => model.Book.PublishingHouse)
            </td>
            <td>
                @Html.DisplayFor(model => model.Book.ReleaseDate)
            </td>
        </tr>
    </table>
</fieldset>

@if (ViewBag.DateInfo != null)
{
    <h4>Prawdopodobny termin dostepności książki: @ViewBag.DateInfo </h4>
}
else
{
    <h4>Prawdopodobny termin dostepności książki: @Html.DisplayFor(model => model.PropablyBookAvailableDate)</h4>    
}

<br />
<p>
    @Html.ActionLink("Wstecz", "Index", "Book", null, new { @class = "button" })
</p>

BooksLibrary/Views/Book/DeleteBook.cshtml
@model BooksLibrary.Models.BookViewModels.BookViewModel

@{
    ViewBag.Title = "Usuń książkę";
}

<h2>Usuń książkę</h2>

<h3>Czy na pewno chcesz usunąć wybraną książkę?</h3>
<fieldset>
    <legend>Książka</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Author)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Author)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ISBN)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ISBN)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PublishingHouse)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PublishingHouse)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ReleaseDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ReleaseDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Quantity)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Quantity)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.Hidden("returnUrl",(object)ViewBag.ReturnUrl)
    <p>
        <input type="submit" value="Usuń" class ="button" />
        @Html.ActionLink("Anuluj", "RedirectToReferrerUrl", new { @returnUrl = ViewBag.ReturnUrl }, new { @class = "button" })
    </p>
}

BooksLibrary/Views/Book/Details.cshtml
@model BooksLibrary.Models.BookViewModels.BookViewModel

@{
    ViewBag.Title = "Szczegóły";
}

<h2>Szczegóły</h2>

<fieldset>
    <legend>Szczegóły</legend>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Author)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Author)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.ISBN)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ISBN)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.PublishingHouse)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PublishingHouse)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.ReleaseDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ReleaseDate)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Quantity)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Quantity)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Wstecz", "Back", new { @returnUrl = Request.UrlReferrer }, new { @class = "button" })
</p>

BooksLibrary/Views/Book/Index.cshtml
@using BooksLibrary.HtmlHelperClass;
@using PagedList.Mvc;
@using PagedList;
@model IPagedList<BooksLibrary.Models.IndexAllBooksViewModel>

@{
    ViewBag.Title = "Lista książek";
}
<link href="~/Content/PagedList.css" rel="stylesheet" />

<h2>Lista książek</h2>

<div id="categories">
    @{Html.RenderAction("CategoriesPartial", "Category", new { selectedCategory = ViewBag.CategoryFilter, management = false });}
</div>

@using (Html.BeginForm("Index", "Book", FormMethod.Get))
{
    @Html.Hidden("categoryFilter", ViewBag.CategoryFilter as string)
    <input type="hidden" id="selectedCategory" value="category" />
    <p>
        Tytył książki: @Html.TextBox("searchBook", ViewBag.SearchBook as string)
        Autor: @Html.TextBox("searchAuthor", ViewBag.SearchAuthor as string)
        <input type="submit" value="Szukaj" />
    </p>
}

<table>
    <tr>
        <th>
            @Html.ActionLink("Tytuł", "Index", new { sortOrder = "title" })
        </th>
        <th>
            @Html.ActionLink("Autor", "Index", new { sortOrder = "author" })
        </th>
        <th>Kategoria
        </th>
        <th>Dostępna
        </th>
        <th>Opcje
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @Html.QuantityToYesOrNo(item.Quantity)
            </td>
            <td>
                @Html.ActionLink("Szczegóły", "Details", new { bookId = item.BookId })
                @Html.ActionLink("Zarazerwuj", "AddReservation", "Reservation", new { bookId = item.BookId }, null)
            </td>
        </tr>
    }

</table>
<br />

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, searchBook = ViewBag.SearchBook, searchAuthor = ViewBag.SearchAuthor, sortOrder = ViewBag.SortOrder, categoryFilter = ViewBag.CategoryFilter }))

BooksLibrary/Views/Book/IndexBookManagement.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<BooksLibrary.Models.BookViewModels.BookViewModel>

@{
    ViewBag.Title = "Książki";
}
<link href="~/Content/PagedList.css" rel="stylesheet" />

<h2>Książki</h2>

<p style="margin-bottom:10px">
    @Html.ActionLink("Dodaj książkę", "AddBook", null, new { @class = "button" })
</p>

<div id="categories">
    @{Html.RenderAction("CategoriesPartial", "Category", new { selectedCategory = ViewBag.CategoryFilter, management = true });}
</div>

<br />
@using (Html.BeginForm("IndexBookManagement", "Book", FormMethod.Get))
{
    <p>
        Tytył książki: @Html.TextBox("searchBook", ViewBag.SearchBook as string)
        Autor: @Html.TextBox("searchAuthor", ViewBag.SearchAuthor as string)
        <input type="submit" value="Szukaj" />
    </p>    
}

<table>
    <tr>
        <th>Tytuł
        </th>
        <th>Autor
        </th>
        <th>ISBN
        </th>
        <th>Wydawnictwo
        </th>
        <th>Data wydania
        </th>
        <th>Ilość
        </th>
        <th>Opcje
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ISBN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PublishingHouse)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.ActionLink("Edytuj", "EditBook", new { bookId = item.BookId })
                @Html.ActionLink("Usuń", "DeleteBook", new { bookId = item.BookId })
            </td>
        </tr>
    }

</table>
<br />

@Html.PagedListPager(Model, page => Url.Action("IndexBookManagement", new { page, searchBook = ViewBag.SearchBook, searchAuthor = ViewBag.SearchAuthor }))